id: IC9C303E9
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T21:44:55.150866'
last_modified: '2022-05-30T21:44:55.150871'
parser: null
source_metadata:
  title: Jatsön Nyingpo Series
  language: bo
  description: 'Texts by and about the treasure-revealer Jatsön Nyingpo (’ja’ tshon
    snying po, 1585–1656), whose revelations include the famous Könchok Chidü (dkon
    mchog spyi ’dus) or ''Embodiment of the Three Jewels'':'
  volume:
    fD45A:
      title: The Guidebook to the Hidden Land of Pemokö
      base_file: fD45A.txt
      order: 1
      parent: Guidebooks
    fE221:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      base_file: fE221.txt
      order: 2
      parent: Offering
    f9CA3:
      title: Prayer to Rigdzin Jatsön Nyingpo
      base_file: f9CA3.txt
      order: 3
      parent: Prayers
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
